draw_set_font(global.thenfont)
draw_set_color(c_white)
draw_set_alpha(1)
draw_set_halign(fa_left)
if !done {
    draw_window(_x[1]-16,_y[1]-40,11,4)
    draw_window(_x[1]+72,_y[1]-40,20,4)
    draw_window(_x[1]-16,_y[1]-8,31,16)
    switch player {
        case 1: 
            draw_text(_x[1]+88,y-22,string_hash_to_newline(name_question[1]))
            break
        case 2: 
            draw_text(_x[1]+88,y-22,string_hash_to_newline(name_question[2])) 
            break
        case 3: 
            draw_text(_x[1]+88,y-22,string_hash_to_newline(name_question[3])) 
            break
        case 4: 
            draw_text(_x[1]+88,y-22,string_hash_to_newline(name_question[4])) 
            break
        case 5: 
            draw_text(_x[1]+88,y-22,string_hash_to_newline(food_question)) 
            break
        case 6: 
            draw_text(_x[1]+88,y-22,string_hash_to_newline(thing_question)) 
            break
    }
    draw_text(x+8,y-22,string_hash_to_newline(the_string))
    draw_sprite(sprTextCursor,cursor_image_index,x+8+string_width(string_hash_to_newline(the_string)),y-22)
    
    if capital {
        draw_text(_x[1],_y[1],string_hash_to_newline("A"))
        draw_text(_x[2],_y[1],string_hash_to_newline("B"))
        draw_text(_x[3],_y[1],string_hash_to_newline("C"))
        draw_text(_x[4],_y[1],string_hash_to_newline("D"))
        draw_text(_x[5],_y[1],string_hash_to_newline("E"))
        draw_text(_x[6],_y[1],string_hash_to_newline("F"))
        draw_text(_x[7],_y[1],string_hash_to_newline("G"))
        draw_text(_x[8],_y[1],string_hash_to_newline("H"))
        draw_text(_x[9],_y[1],string_hash_to_newline("I"))
        draw_text(_x[10],_y[1],string_hash_to_newline(" "))
        draw_text(_x[11],_y[1],string_hash_to_newline(" "))
        draw_text(_x[12],_y[1],string_hash_to_newline("-"))
        draw_text(_x[13],_y[1],string_hash_to_newline("@"))
        draw_text(_x[14],_y[1],string_hash_to_newline("["))
        
        draw_text(_x[1],_y[2],string_hash_to_newline("J"))
        draw_text(_x[2],_y[2],string_hash_to_newline("K"))
        draw_text(_x[3],_y[2],string_hash_to_newline("L"))
        draw_text(_x[4],_y[2],string_hash_to_newline("M"))
        draw_text(_x[5],_y[2],string_hash_to_newline("N"))
        draw_text(_x[6],_y[2],string_hash_to_newline("O"))
        draw_text(_x[7],_y[2],string_hash_to_newline("P"))
        draw_text(_x[8],_y[2],string_hash_to_newline("Q"))
        draw_text(_x[9],_y[2],string_hash_to_newline("R"))
        draw_text(_x[10],_y[2],string_hash_to_newline(" "))
        draw_text(_x[11],_y[2],string_hash_to_newline(" "))
        draw_text(_x[12],_y[2],string_hash_to_newline("'"))
        draw_text(_x[13],_y[2],string_hash_to_newline("~"))
        draw_text(_x[14],_y[2],string_hash_to_newline("\\"))
        
        draw_text(_x[1],_y[3],string_hash_to_newline("S"))
        draw_text(_x[2],_y[3],string_hash_to_newline("T"))
        draw_text(_x[3],_y[3],string_hash_to_newline("U"))
        draw_text(_x[4],_y[3],string_hash_to_newline("V"))
        draw_text(_x[5],_y[3],string_hash_to_newline("W"))
        draw_text(_x[6],_y[3],string_hash_to_newline("X"))
        draw_text(_x[7],_y[3],string_hash_to_newline("Y"))
        draw_text(_x[8],_y[3],string_hash_to_newline("Z"))
        draw_text(_x[9],_y[3],string_hash_to_newline("Space"))
        draw_text(_x[10],_y[3],string_hash_to_newline(" "))
        draw_text(_x[11],_y[3],string_hash_to_newline(" "))
        draw_text(_x[12],_y[3],string_hash_to_newline("."))
        draw_text(_x[13],_y[3],string_hash_to_newline("/"))
        draw_text(_x[14],_y[3],string_hash_to_newline("]"))
    
    } else {
        draw_text(_x[1],_y[1],string_hash_to_newline("a"))
        draw_text(_x[2],_y[1],string_hash_to_newline("b"))
        draw_text(_x[3],_y[1],string_hash_to_newline("c"))
        draw_text(_x[4],_y[1],string_hash_to_newline("d"))
        draw_text(_x[5],_y[1],string_hash_to_newline("e"))
        draw_text(_x[6],_y[1],string_hash_to_newline("f"))
        draw_text(_x[7],_y[1],string_hash_to_newline("g"))
        draw_text(_x[8],_y[1],string_hash_to_newline("h"))
        draw_text(_x[9],_y[1],string_hash_to_newline("i"))
        draw_text(_x[10],_y[1],string_hash_to_newline(" "))
        draw_text(_x[11],_y[1],string_hash_to_newline(" "))
        draw_text(_x[12],_y[1],string_hash_to_newline("-"))
        draw_text(_x[13],_y[1],string_hash_to_newline("@"))
        draw_text(_x[14],_y[1],string_hash_to_newline("["))
        
        draw_text(_x[1],_y[2],string_hash_to_newline("j"))
        draw_text(_x[2],_y[2],string_hash_to_newline("k"))
        draw_text(_x[3],_y[2],string_hash_to_newline("l"))
        draw_text(_x[4],_y[2],string_hash_to_newline("m"))
        draw_text(_x[5],_y[2],string_hash_to_newline("n"))
        draw_text(_x[6],_y[2],string_hash_to_newline("o"))
        draw_text(_x[7],_y[2],string_hash_to_newline("p"))
        draw_text(_x[8],_y[2],string_hash_to_newline("q"))
        draw_text(_x[9],_y[2],string_hash_to_newline("r"))
        draw_text(_x[10],_y[2],string_hash_to_newline(" "))
        draw_text(_x[11],_y[2],string_hash_to_newline(" "))
        draw_text(_x[12],_y[2],string_hash_to_newline("'"))
        draw_text(_x[13],_y[2],string_hash_to_newline("~"))
        draw_text(_x[14],_y[2],string_hash_to_newline("\\"))
        
        draw_text(_x[1],_y[3],string_hash_to_newline("s"))
        draw_text(_x[2],_y[3],string_hash_to_newline("t"))
        draw_text(_x[3],_y[3],string_hash_to_newline("u"))
        draw_text(_x[4],_y[3],string_hash_to_newline("v"))
        draw_text(_x[5],_y[3],string_hash_to_newline("w"))
        draw_text(_x[6],_y[3],string_hash_to_newline("x"))
        draw_text(_x[7],_y[3],string_hash_to_newline("y"))
        draw_text(_x[8],_y[3],string_hash_to_newline("z"))
        draw_text(_x[9],_y[3],string_hash_to_newline("Space"))
        draw_text(_x[10],_y[3],string_hash_to_newline(" "))
        draw_text(_x[11],_y[3],string_hash_to_newline(" "))
        draw_text(_x[12],_y[3],string_hash_to_newline("."))
        draw_text(_x[13],_y[3],string_hash_to_newline("/"))
        draw_text(_x[14],_y[3],string_hash_to_newline("]"))
    }
    
    draw_text(_x[1],_y[4],string_hash_to_newline("0"))
    draw_text(_x[2],_y[4],string_hash_to_newline("1"))
    draw_text(_x[3],_y[4],string_hash_to_newline("2"))
    draw_text(_x[4],_y[4],string_hash_to_newline("3"))
    draw_text(_x[5],_y[4],string_hash_to_newline("4"))
    draw_text(_x[6],_y[4],string_hash_to_newline("5"))
    draw_text(_x[7],_y[4],string_hash_to_newline("6"))
    draw_text(_x[8],_y[4],string_hash_to_newline("7"))
    draw_text(_x[9],_y[4],string_hash_to_newline("8"))
    draw_text(_x[10],_y[4],string_hash_to_newline("9"))
    draw_text(_x[11],_y[4],string_hash_to_newline(" "))
    draw_text(_x[12],_y[4],string_hash_to_newline("!"))
    draw_text(_x[13],_y[4],string_hash_to_newline("|"))
    draw_text(_x[14],_y[4],string_hash_to_newline("^"))
    
    draw_text(_x[1],_y[5],string_hash_to_newline("CAPITAL"))
    draw_text(_x[5],_y[5],string_hash_to_newline("small"))
    draw_text(_x[12],_y[5],string_hash_to_newline("?"))
    draw_text(_x[13],_y[5],string_hash_to_newline("$"))
    draw_text(_x[14],_y[5],string_hash_to_newline("_"))
    
    draw_text(_x[1],_y[6],string_hash_to_newline("I don't care"))
    draw_text(_x[10],_y[6],string_hash_to_newline("Backspace"))
    draw_text(_x[14],_y[6],string_hash_to_newline("OK"))
    draw_sprite(spr_cursor,cursor_image_index,cursor_x-3,cursor_y+7)

} else {
    draw_sprite(sprProtag_f_d,cursor_image_index/2,_x[1],_y[1]-16)
    draw_window(_x[1]+16,_y[1]-40,11,4)
    draw_sprite(sprProtag_f_d,cursor_image_index/2,_x[1],_y[1]+16)
    draw_window(_x[1]+16,_y[1]-8,11,4)
    draw_sprite(sprProtag_f_d,cursor_image_index/2,_x[1],_y[1]+48)
    draw_window(_x[1]+16,_y[1]+24,11,4)
    draw_sprite(sprProtag_f_d,cursor_image_index/2,_x[1],_y[1]+80)
    draw_window(_x[1]+16,_y[1]+56,11,4)
    
    draw_window(_x[1]+104,_y[1]-40,16,6)
    draw_window(_x[1]+104,_y[1]+24,16,6)
    draw_window(_x[1]-16,_y[6]-8,31,4)
    draw_text(_x[3],_y[1]-30,string_hash_to_newline(global.s_name[1]))
    draw_text(_x[3],_y[1]+2,string_hash_to_newline(global.s_name[2]))
    draw_text(_x[3],_y[1]+34,string_hash_to_newline(global.s_name[3]))
    draw_text(_x[3],_y[1]+66,string_hash_to_newline(global.s_name[4]))
    draw_text(_x[8]+4,_y[1]-30,string_hash_to_newline("Favourite food"+":"))
    draw_text(_x[8]+4,_y[5]-30,string_hash_to_newline("Coolest thing"+":"))
    draw_text(_x[1],_y[6]+2,string_hash_to_newline("Is this okay?"))
    draw_text(_x[10],_y[6]+2,string_hash_to_newline("Yes"))
    draw_text(_x[14],_y[6]+2,string_hash_to_newline("No"))
    draw_set_halign(fa_right)
    draw_text(_x[14]+12,_y[1]-30,string_hash_to_newline("#"+global.favfood))
    draw_text(_x[14]+12,_y[5]-30,string_hash_to_newline("#"+global.favthing))
    draw_sprite(spr_cursor,cursor_image_index,cursor_x-3,cursor_y+9)
}


